rg_name_1               = "myLabResourceGroup1"
region_1                = "northeurope"
tag_environment         = "Lab"
tag_createdby           = "Your Name"
tag_createdwith         = "Terraform"
tag_project             = "Blog"
prefix                  = "Lab"
labadmin                = "labadmin"
smb_server      = "ANF"
dns_server      = "10.0.0.1"
domain          = "your-domain.local"
ou              = "OU=ANF"
cap_pool_tier     = "Standard"
cap_pool_size     = "4"
qos_type          = "Auto"
