rg_name_1               = "myLabResourceGroup1"
region_1                = "northeurope"
tag_environment         = "Lab"
tag_createdby           = "Your Name"
tag_createdwith         = "Terraform"
tag_project             = "Blog"
prefix                  = "Lab"
labadmin                = "labadmin"